[package]
name = "color-checker"
version = "0.1.0"
authors = ["masahiko-ofgp <ichigyo.zanmai@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Simple color checker."

[dependencies.sdl2]
version = "0.33.0"
